# Generated by Django 3.2.12 on 2022-03-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20220309_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
