# Generated by Django 3.2.12 on 2022-03-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_paper_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
