# Generated by Django 3.2.12 on 2022-03-10 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20220310_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.TextField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=100, null=True)),
                ('abstracts', models.TextField(blank=True, null=True)),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.paper')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
