# Generated by Django 3.2.12 on 2022-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_paper_upvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
