# Generated by Django 3.2.12 on 2022-03-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_delete_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('paper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.paper')),
            ],
        ),
    ]
