# Generated by Django 3.2.12 on 2022-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='paper',
        ),
        migrations.AddField(
            model_name='upvote',
            name='paper_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
