# Generated by Django 3.2.12 on 2022-03-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0013_alter_user_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
